apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-alertmanager
  namespace: monitoring-poc
  labels:
    grafana_datasource: "1"
data:
  alertmanager.yaml: |
    apiVersion: 1
    datasources:
      - name: "alertmanager"
        type: alertmanager
        uid: alertmanager
        url: http://vmalertmanager-vm.monitoring.svc.cluster.local.:9093/
        access: proxy
        jsonData:
          handleGrafanaManagedAlerts: false
          implementation: prometheus
