apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-tempo
  namespace: monitoring-poc
  labels:
    grafana_datasource: "1"
data:
  tempo.yaml: |
    apiVersion: 1
    datasources:
      - name: tempo
        type: tempo
        uid: tempo
        orgId: 2
        url: http://tempo-gateway.observability-poc.svc.cluster.local:80
        access: proxy
        basicAuth: false
        jsonData:
          httpHeaderName1: "X-Scope-OrgID"
          httpHeaderName2: "Authorization"
          grpcInsecure: true
          streamingEnabled:
            search: false
            metrics: false
        secureJsonData:
          httpHeaderValue1: "caprinno"
          httpHeaderValue2: "Basic Y2Fwcmlubm86dlVWdUdCUVE1RlI4SjYrYlRWU0ZWQT09"
        editable: true
