apiVersion: v1
kind: ConfigMap

metadata:
  name: grafana-datasources
  namespace: monitoring-poc
  labels:
    grafana_datasource: "1"

data:
  victoria-metrics.yaml: |
    apiVersion: 1

    datasources:
      - name: VictoriaMetrics
        type: prometheus
        access: proxy
        isDefault: true

        url: http://vmauth-vmauth.monitoring-poc.svc:8427/select/100/prometheus

        basicAuth: true
        basicAuthUser: tenant1

        secureJsonData:
          basicAuthPassword: password1

        jsonData:
          timeInterval: 30s
          httpMethod: POST 
