vm:
  victoria-metrics-operator:
    enabled: true
    fullnameOverride: vm-operator
    operator:
      disable_prometheus_converter: false
    crds:
      plain: false
      cleanup:
        enabled: false
    serviceMonitor:
      enabled: true
    image:
      registry: "quay.io"
      repository: victoriametrics/operator
    env:
      - name: "VM_USECUSTOMCONFIGRELOADER"
        value: "true"
      - name: VM_CUSTOMCONFIGRELOADERIMAGE
        value: "quay.io/victoriametrics/operator:config-reloader-v0.53.0"
      - name: VM_VLOGSDEFAULT_IMAGE
        value: "quay.io/victoriametrics/victoria-logs"
      - name: "VM_VMALERTDEFAULT_IMAGE"
        value: "quay.io/victoriametrics/vmalert"
      - name: "VM_VMAGENTDEFAULT_IMAGE"
        value: "quay.io/victoriametrics/vmagent"
      - name: "VM_VMSINGLEDEFAULT_IMAGE"
        value: "quay.io/victoriametrics/victoria-metrics"
      - name: "VM_VMCLUSTERDEFAULT_VMSELECTDEFAULT_IMAGE"
        value: "quay.io/victoriametrics/vmselect"
      - name: "VM_VMCLUSTERDEFAULT_VMSTORAGEDEFAULT_IMAGE"
        value: "quay.io/victoriametrics/vmstorage"
      - name: "VM_VMCLUSTERDEFAULT_VMINSERTDEFAULT_IMAGE"
        value: "quay.io/victoriametrics/vminsert"
      - name: "VM_VMBACKUP_IMAGE"
        value: "quay.io/victoriametrics/vmbackupmanager"
      - name: "VM_VMAUTHDEFAULT_IMAGE"
        value: "quay.io/victoriametrics/vmauth"
      - name: "VM_VMALERTMANAGER_ALERTMANAGERDEFAULTBASEIMAGE"
        value: "quay.io/prometheus/alertmanager"
      - name: "VM_CONFIG_RELOADER_REQUEST_CPU"
        value: "unlimited"
      - name: "VM_CONFIG_RELOADER_REQUEST_MEMORY"
        value: "unlimited"
      - name: "VM_CONFIG_RELOADER_LIMIT_CPU"
        value: "unlimited"
      - name: "VM_CONFIG_RELOADER_LIMIT_MEMORY"
        value: "unlimited"
      - name: "VM_VMAGENTDEFAULT_USEDEFAULTRESOURCES"
        value: "false"
      - name: "VM_VMALERTMANAGER_USEDEFAULTRESOURCES"
        value: "false"

  vmsingle:
    enabled: false

  vmcluster:
    enabled: true
    spec:
      retentionPeriod: 1d
      replicationFactor: 1
      vmstorage:
        replicaCount: 2
        extraArgs:
          search.maxUniqueTimeseries: "10000000000000"
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: "0.5"
            memory: 1Gi
        storage:
          volumeClaimTemplate:
            spec:
              resources:
                requests:
                  storage: 5Gi
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: vmstorage
                topologyKey: kubernetes.io/hostname
      vmselect:
        enabled: true
        replicaCount: 2
        extraArgs:
          memory.allowedPercent: "75"
          search.cacheTimestampOffset: 60m
          search.maxLabelsAPISeries: "10000000000000"
          search.maxMemoryPerQuery: 2GB
          search.maxPointsPerTimeseries: "10000000000000"
          search.maxQueryDuration: 10m
          search.maxQueryLen: "10000000000000"
          search.maxSeries: "10000000000000"
          search.maxUniqueTimeseries: "10000000000000"
        cacheMountPath: "/select-cache"
        storage:
          volumeClaimTemplate:
            spec:
              resources:
                requests:
                  storage: 1Gi
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: vmselect
                topologyKey: kubernetes.io/hostname
      vminsert:
        enabled: true
        replicaCount: 2
        extraArgs:
          maxLabelsPerTimeseries: "100"
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: vminsert
                topologyKey: kubernetes.io/hostname

  alertmanager:
    enabled: true
    spec:
      replicaCount: 1

  vmalert:
    enabled: true
    spec:
      selectAllByDefault: true
      evaluationInterval: 15s
      datasource:
        - url: "http://vmselect-vm.monitoring-poc.svc:8481/select/99/prometheus"
      remoteWrite:
        - url: "http://vminsert-vm.monitoring-poc.svc:8480/insert/99/prometheus/api/v1/write"
      notifiers:
        - url: "http://vmalertmanager-vm.monitoring-poc.svc:9093"

  vmagent:
    enabled: true
    spec:
      selectAllByDefault: true
      serviceScrapeNamespaceSelector: {}
      scrapeInterval: 30s
      remoteWrite:
        - url: "http://vmauth-vmauth.monitoring-poc.svc:8427/insert/99/prometheus/api/v1/write"
          basicAuth:
            username:
              name: vmuser-vmuser-central   # Point to the operator-created secret
              key: username                  # This contains "central-agent"
            password:
              name: vmuser-vmuser-central   # Point to the operator-created secret
              key: password
      extraArgs:
        promscrape.maxScrapeSize: 200MB
        promscrape.dropOriginalLabels: "true"
        remoteWrite.label: cluster=k8s-dev,env=dev
      useVMConfigReloader: false

  kube-state-metrics:
    enabled: true
    extraArgs:
      - --metric-labels-allowlist=pods=[*]
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
      port: 8080
      targetPort: http-metrics
    rbac:
      create: true
    serviceAccount:
      create: true
      name: "kube-sa"
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 20
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 3
    vmScrape:
      enabled: true
      spec:
        selector:
          matchLabels:
            app.kubernetes.io/name: '{{ include "kube-state-metrics.name" (index .Subcharts "kube-state-metrics") }}'
            app.kubernetes.io/instance: '{{ include "vm.release" . }}'
        endpoints:
          - port: http
            honorLabels: true
            metricRelabelConfigs:
              - action: labeldrop
                regex: (uid|container_id|image_id)
              - action: labelmap
                regex: label_(comprinno_.+)
              - action: labeldrop
                regex: label_comprinno_.+
        jobLabel: app.kubernetes.io/name

  defaultRules:
    create: false

  grafana:
    enabled: false

  defaultDashboards:
    enabled: false

  prometheus-node-exporter:
    enabled: true
    spec:
      jobLabel: jobLabel
      selector:
        matchLabels:
          app.kubernetes.io/name: '{{ include "prometheus-node-exporter.name" (index .Subcharts "prometheus-node-exporter") }}'
      endpoints:
        - port: metrics
          metricRelabelConfigs:
            - action: drop
              source_labels: [mountpoint]
              regex: "/var/lib/kubelet/pods.+"

  kubeApiServer:
    enabled: false
  kubeControllerManager:
    enabled: false

prometheus-operator-crds:
  enabled: true
