prometheus-operator-crds:
  enabled: false

vm:
  enabled: true

  victoria-metrics-operator:
    enabled: true
    fullnameOverride: vm-operator
    replicaCount: 1
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: victoria-metrics-operator
              topologyKey: kubernetes.io/hostname
    crds:
      plain: false
      cleanup:
        enabled: false
        image:
          repository: bitnami/kubectl
          pullPolicy: IfNotPresent
    serviceMonitor:
      enabled: true
    operator:
      disable_prometheus_converter: false
    image:
      registry: "quay.io"
      repository: victoriametrics/operator
    env:
      - name: VM_USECUSTOMCONFIGRELOADER
        value: "true"
      - name: VM_CUSTOMCONFIGRELOADERIMAGE
        value: "quay.io/victoriametrics/operator:config-reloader-v0.53.0"
      - name: VM_VLOGSDEFAULT_IMAGE
        value: "quay.io/victoriametrics/victoria-logs"
      - name: VM_VMALERTDEFAULT_IMAGE
        value: "quay.io/victoriametrics/vmalert"
      - name: VM_VMAGENTDEFAULT_IMAGE
        value: "quay.io/victoriametrics/vmagent"
      - name: VM_VMSINGLEDEFAULT_IMAGE
        value: "quay.io/victoriametrics/victoria-metrics"
      - name: VM_VMCLUSTERDEFAULT_VMSELECTDEFAULT_IMAGE
        value: "quay.io/victoriametrics/vmselect"
      - name: VM_VMCLUSTERDEFAULT_VMSTORAGEDEFAULT_IMAGE
        value: "quay.io/victoriametrics/vmstorage"
      - name: VM_VMCLUSTERDEFAULT_VMINSERTDEFAULT_IMAGE
        value: "quay.io/victoriametrics/vminsert"
      - name: VM_VMBACKUP_IMAGE
        value: "quay.io/victoriametrics/vmbackupmanager"
      - name: VM_VMAUTHDEFAULT_IMAGE
        value: "quay.io/victoriametrics/vmauth"
      - name: VM_VMALERTMANAGER_ALERTMANAGERDEFAULTBASEIMAGE
        value: "quay.io/prometheus/alertmanager"
      - name: VM_CONFIG_RELOADER_REQUEST_CPU
        value: "unlimited"
      - name: VM_CONFIG_RELOADER_REQUEST_MEMORY
        value: "unlimited"
      - name: VM_CONFIG_RELOADER_LIMIT_CPU
        value: "unlimited"
      - name: VM_CONFIG_RELOADER_LIMIT_MEMORY
        value: "unlimited"
      - name: VM_VMAGENTDEFAULT_USEDEFAULTRESOURCES
        value: "false"
      - name: VM_VMALERTMANAGER_USEDEFAULTRESOURCES
        value: "false"

  prometheus-node-exporter:
    enabled: true

  vmsingle:
    enabled: false

  vmcluster:
    enabled: false

  alertmanager:
    enabled: false

  vmalert:
    enabled: false

  vmagent:
    enabled: true
    spec:
      selectAllByDefault: true
      serviceScrapeNamespaceSelector: {}
      scrapeInterval: 30s
      remoteWrite:
        - url: "http://vmauth-vmauth.monitoring-poc.svc:8427/insert/99/prometheus/api/v1/write"
          basicAuth:
            username:
              name: vmuser-vmuser-central   # Point to the operator-created secret
              key: username                  # This contains "central-agent"
            password:
              name: vmuser-vmuser-central   # Point to the operator-created secret
              key: password
      extraArgs:
        promscrape.maxScrapeSize: 200MB
        promscrape.dropOriginalLabels: "true"
        remoteWrite.label: "cluster=k8s-dev,env=dev"
      useVMConfigReloader: true
      resources: {}

  kube-state-metrics:
    enabled: true

  grafana:
    enabled: false

  defaultDashboards:
    enabled: false

  kubeApiServer:
    enabled: false

  kubeControllerManager:
    enabled: false

  defaultRules:
    create: false
