apiVersion: v1
kind: Secret
metadata:
  name: logging-loki-gateway
  namespace: logging-poc

type: Opaque

stringData:
  .htpasswd: |
    caprinno:$apr1$O3WaSHCF$tN3qEeeie5cZtZeeeHVU.1
    pre-prod-tevico-cluster:$apr1$sNZ/4M.K$nb8/3EPcwP63k/XzcuACz1
 
