grafana:
  image:
    repository: grafana/grafana
    tag: "13.0.1"
  service:
    type: NodePort
  useStatefulSet: true
  initChownData:
    enabled: true
  sidecar:
    dashboards:
      enabled: true
    datasources:
      enabled: true
      label: grafana_datasource
      labelValue: "1"
  resources:
    requests:
      cpu: "0.6"
      memory: 700Mi
    limits:
      cpu: "0.8"
      memory: 800Mi
  extraConfigmapMounts:
  persistence:
    enabled: true
    type: sts
    accessModes:
      - ReadWriteOnce
    size: 4Gi
    finalizers:
      - kubernetes.io/pvc-protection
